#!/usr/bin/env bash
# This script runs an infinite loop and displays a message when receiving SIGTERM

trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop to keep the process running
while true; do
    sleep 1
done

