#!/usr/bin/env bash
# This script traps SIGTERM and prints "I am invincible!!!"

trap 'echo "I am invincible!!!"' SIGTERM

# Print OK to signal successful launch
 echo "OK"

# Keep the script alive to wait for signals
while true; do
    sleep 1
done

