#!/usr/bin/env bash
# 7-highlander - Infinite loop with SIGTERM handler

# Trap SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM
 echo "OK"
# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
